### ISSUE TITLE
Cannot find @nodesecure/ci on NPM

### ISSUE THREAD

**Issue by davereid-pfg** [NodeSecure/ci#1]
I cannot use npm to install this project, it's not visible on https://www.npmjs.com/search?q=%40nodesecure as well.

**Comment by fraxken** [comment]
@davereid-pfg Yes we are still working on initial release (which is expected to be available in the coming days/weeks).

**Comment by antoine-coulon** [comment]
@davereid-pfg The package is now available on npm, you should be able to install it :)

**Comment by davereid-pfg** [comment]
Thanks all!
