### ISSUE TITLE
Update to JS-X-Ray v6

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/ci#63]
We need to update JS-X-Ray to the latest major (version 6).

There is probably few breaking changes on warnings & co.

cc @antoine-coulon

**Comment by antoine-coulon** [comment]
Yes we definitely should bump that, I'll take care of it

**Comment by antoine-coulon** [comment]
The major bump of **js-x-ray** to v6 and **scanner** to v4 was just merged.
