### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/ci#64]
Add the CI banner at the top of the README file like in [RC project](https://github.com/NodeSecure/rc)

![ci_banner](https://user-images.githubusercontent.com/4438263/226020356-5790c025-bff1-40d5-b847-360863f53a9a.jpg)

**Comment by Taha-Khan25** [comment]
<p align="center">
  <img src="https://user-images.githubusercontent.com/4438263/216045720-779bf16d-1d35-409f-a0e6-4019bda8edde.jpg" alt="@nodesecure/rc">
</p>

**Comment by Ashish0926** [comment]
Hey @fraxken, can you assign me this issue?

**Comment by Aishu-5** [comment]
i need it

**Comment by fraxken** [comment]
Please be serious if you want to take it (people are opening PR without reading what's requested).

@Ashish0926 You can do it 👍
